export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_USERS_SAGA = 'GET_USERS_SAGA';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_SAGA = 'REGISTER_USER_SAGA';

export const REGISTER_USER_RESET_STATE = 'REGISTER_USER_RESET_STATE';
export const REGISTER_USER_RESET_STATE_SAGA = 'REGISTER_USER_RESET_STATE_SAGA';

export const GET_TOTAL_NUMBER_OF_USERS_REQUEST =
  'GET_TOTAL_NUMBER_OF_USERS_REQUEST';
export const GET_TOTAL_NUMBER_OF_USERS_SUCCESS =
  'GET_TOTAL_NUMBER_OF_USERS_SUCCESS';
export const GET_TOTAL_NUMBER_OF_USERS_FAIL = 'GET_TOTAL_NUMBER_OF_USERS_FAIL';
export const GET_TOTAL_NUMBER_OF_USERS_SAGA = 'GET_TOTAL_NUMBER_OF_USERS_SAGA';
